// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gsxhnd/tower/src/utils"
)

// Injectors from wire.go:

func InitApp() *application {
	config := utils.NewConfig()
	wireApplication := NewApplication(config)
	return wireApplication
}
