// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/gsxhnd/tower/src/mqtt"
	"github.com/gsxhnd/tower/src/utils"
)

// Injectors from wire.go:

func InitApp(filePath *string) (*application, error) {
	engine := gin.New()
	logger := utils.NewLogger()
	tracerProvider, err := utils.NewTracer()
	if err != nil {
		return nil, err
	}
	config, err := utils.NewConfig(filePath)
	if err != nil {
		return nil, err
	}
	utilsUtils, err := utils.NewUtils(logger, tracerProvider, config)
	if err != nil {
		return nil, err
	}
	mqttClient := mqtt.NewMqttClient()
	wireApplication := NewApplication(engine, utilsUtils, mqttClient)
	return wireApplication, nil
}
