// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/gsxhnd/tower/src/handler"
	"github.com/gsxhnd/tower/src/middleware"
	"github.com/gsxhnd/tower/src/mqtt"
	"github.com/gsxhnd/tower/src/routes"
	"github.com/gsxhnd/tower/src/utils"
)

// Injectors from wire.go:

func InitApp(filePath *string) (*application, error) {
	engine := gin.New()
	mqttClient := mqtt.NewMqttClient()
	config, err := utils.NewConfig(filePath)
	if err != nil {
		return nil, err
	}
	logger := utils.NewLogger(config)
	middlewarer := middleware.NewMiddleware(logger)
	rootHandler := handler.NewRootHandle(logger)
	routesRoutes := &routes.Routes{
		Middleware: middlewarer,
		RootHandle: rootHandler,
	}
	wireApplication := NewApplication(engine, mqttClient, routesRoutes)
	return wireApplication, nil
}
